# Introduction to NumPy Arrays

1. NumPy N-dimensional Array.
2. Functions to Create Arrays.
    * Empty.
    * Zeros.
    * Ones.
    * Other array creation routines.
3. Creating Arrays from Lists.
    * From List to 1-D Array.
    * From List of Lists to 2-D Array.
4. Combining Arrays.
    * Vertical Stack.
    * Horizontal Stack.
5. Array Indexing.
    * 1-D Indexing.
    * 2-D Indexing.
6. Array Slicing.
    * 1-D Slicing.
    * 2-D Slicing.
7. Array Reshaping.
    * Shape attribute
    * Reshape 1D to 2D Array.
    * Reshape 2D to 3D Array.

## 1. NumPy N-dimensional Array.

In [1]:
from numpy import array

l = [1.0, 2.0, 3.0]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


#### List of array atributes:

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-attributes

## 2. Functions to Create Arrays.

### Empty

In [2]:
from numpy import empty

a = empty([3,3])
print(a)
print(a.astype('int'))

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 3.67584841e-321]
 [1.69117157e-306 6.23059725e-307 9.34597568e-307]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Zeros

In [3]:
from numpy import zeros

a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones

In [4]:
from numpy import ones

a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


### Other array creation routines:

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html

## 3. Creating Arrays from Lists.

### From List to 1-D Array

In [5]:
data = [11, 22, 33, 44, 55]
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


### From List of Lists to 2-D Array

In [6]:
data = [
    [11, 22],
    [33, 44],
    [55, 66]
]
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## 4. Combining Arrays.

### Vertical Stack

In [7]:
from numpy import vstack

a1 = array([1,2,3])
a2 = array([4,5,6])

a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### Horizontal Stack

In [8]:
from numpy import hstack

a1 = array([1,2,3])
a2 = array([4,5,6])

a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


## 5. Array Indexing.

### 1-D Indexing

In [9]:
data = array([11, 22, 33, 44, 55])
print(data[0])
print(data[4])

11
55


#### Negative indexing

In [10]:
print(data[-1])
print(data[-5])

55
11


### 2-D Indexing

In [11]:
data = array([[11, 22], [33, 44], [55, 66]])
print(data[0,0])
print(data[2,1])
print(data[0,])

11
66
[11 22]


## 6. Array Slicing.

### 1-D Slicing

In [12]:
data = array([11, 22, 33, 44, 55])
print(data[:])
print(data[0:1])

[11 22 33 44 55]
[11]


#### Using negative indexes

In [13]:
data = array([11, 22, 33, 44, 55])
print(data[-2:])
print(data[:-2])
print(data[::-1])

[44 55]
[11 22 33]
[55 44 33 22 11]


### 2-D Slicing

#### Split Input and Output Features

In [14]:
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])

X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


#### Split Train and Test Rows

In [15]:
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])

split = 2
train, test = data[:split, :], data[split:, :]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## 7. Array Reshaping.

### Shape attribute

#### 1-D array

In [16]:
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


#### 2-D array

In [17]:
data = [[11, 22],
        [33, 44],
        [55, 66]]

data = array(data)
print(data.shape)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

(3, 2)
Rows: 3
Cols: 2


### Reshape 1D to 2D Array

In [18]:
data = array([11, 22, 33, 44, 55])
print(data.shape)

data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


### Reshape 2D to 3D Array

In [19]:
data = [[11, 22],
        [33, 44],
        [55, 66]]

data = array(data)
print(data.shape)

data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


#### More on NumPy arrays slicing and indexing:

https://numpy.org/doc/stable/reference/arrays.indexing.html