# Introduction to Vectors for Machine Learning

1. What is a Vector?
2. Defining a Vector in NumPy.
3. Vector Arithmetic.
* Addition.
* Subtraction.
* Multiplication.
* Division.
4. Vector Dot Product.
5. Vector-Scalar Operations.
* Addition.
* Subtraction.
* Multiplication.
* Division.
6. Vector Norm.
* Vector L1 Norm
* Vector L2 Norm
* Vector Max Norm

## 1. What is a Vector?

A vector is a tuple of one or more values called scalars.

## 2. Defining a Vector in NumPy.

In [1]:
from numpy import array

v = array([1, 2, 3])
print(v)

[1 2 3]


## 3. Vector Arithmetic.

### Vector Addition

In [2]:
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a + b
print(c)

[2 4 6]


### Vector Subtraction

In [3]:
a = array([1, 2, 3])
b = array([0.5, 0.5, 0.5])
c = a - b
print(c)

[0.5 1.5 2.5]


### Vector Multiplication

In [4]:
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a * b
print(c)

[1 4 9]


### Vector Division

In [5]:
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a / b
print(c)

[1. 1. 1.]


In [6]:
c = a // b
print(c)

[1 1 1]


In [7]:
c = a % b
print(c)

[0 0 0]


## 4. Vector Dot Product.

The dot product is the key tool for calculating vector projections, vector decompositions, and determining orthogonality. The name dot product comes from the symbol used to denote it.

The operation can be used in machine learning to calculate the weighted sum of a vector.

In [8]:
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a.dot(b)
print(c)

14


## 5. Vector-Scalar Operations.

In [9]:
v = array([1, 2, 3])
s = 0.5

### Vector-Scalar addition

In [10]:
c = s + v
print(c)

[1.5 2.5 3.5]


### Vector-Scalar subtraction

In [11]:
c = v - s
print(c)

[0.5 1.5 2.5]


### Vector-Scalar multiplication

In [12]:
c = s * v
print(c)

[0.5 1.  1.5]


### Vector-Scalar division

In [13]:
v = array([1, 2, 3])
s = 2

c = v / s
print(c)

[0.5 1.  1.5]


In [14]:
c = v // s
print(c)

[0 1 1]


In [15]:
c = v % s
print(c)

[1 0 1]


## 6. Vector Norm

The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector’s magnitude or the norm.

### Vector L1 Norm

The length of a vector can be calculated using the L1 norm, where the 1 is a superscript of the L, e.g. L^1.

The notation for the L1 norm of a vector is ||v||1, where 1 is a subscript. As such, this length is sometimes called the **taxicab norm or the Manhattan norm**.

**The L1 norm is calculated as the sum of the absolute vector values**, where the absolute value of a scalar uses the notation |a1|. In effect, the norm is a calculation of the Manhattan distance from the origin of the vector space.

In [16]:
from numpy.linalg import norm

v = array([1, 2, 3])
l1 = norm(v, 1)
print(l1)

6.0


### Vector L2 Norm

The L2 norm calculates the distance of the vector coordinate from the origin of the vector space. **As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin**. The result is a positive distance value.

The L2 norm is calculated as the square root of the sum of the squared vector values.

In [17]:
v = array([1, 2, 3])
l2 = norm(v)
print(l2)

3.7416573867739413


By far, the L2 norm is more commonly used than other vector norms in machine learning.

### Vector Max Norm

Max norm of a vector is referred to as L^inf where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is ||x||inf, where inf is a subscript.

The max norm is calculated as returning the **maximum value of the vector**, hence the name.

In [18]:
from numpy import inf

v = array([1, 2, 3])
maxnorm = norm(v, inf)
print(maxnorm)

3.0


Max norm is also used as a regularization in machine learning, such as on neural network weights, called **max norm regularization**.

https://en.wikipedia.org/wiki/Norm_(mathematics)