# Introduction to Tensors for Machine Learning

1. What are Tensors?
2. Tensors in NumPy.
3. Element-Wise Tensor Operations.
    * Tensor Addition.
    * Tensor Subtraction.
    * Tensor Hadamard Product.
    * Tensor Division.
4. Tensor Product.
    * Tensordot with vectors.
    * Tensordot with matrices.
    * Tensordot with tensors.
    * Understanding tensordot.
    * Outer product.

## 1. What are Tensors?

* A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.
* Tensor notation is much like matrix notation with a capital letter representing a tensor and lowercase letters with subscript integers representing scalar values within the tensor.
* Many of the operations that can be performed with scalars, vectors, and matrices can be reformulated to be performed with tensors.
* As a tool, tensors and tensor algebra is widely used in the fields of physics and engineering. It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.

## 2. Tensors in NumPy.

In [1]:
from numpy import array

# List of lists of lists for a 3-D Tensor
T = [
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
]

T = array(T)
print(T.shape)
# The tensor is printed as a list of matrices
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


## 3. Element-Wise Tensor Operations.

### Tensor Addition

In [2]:
A = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

B = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


### Tensor Subtraction

In [3]:
A = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

B = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### Tensor Hadamard Product

In [4]:
A = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

B = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


### Tensor Division

In [5]:
A = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

B = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
C = A // B
print(C)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
C = A % B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## 4. Tensor Product.

* The tensor product operator is often denoted as **a circle with a small x in the middle**. We will denote it here as “(x)”.
* Given a tensor A with q dimensions and tensor B with r dimensions, **the product of these tensors will be a new tensor with the order of q + r or, said another way, q + r dimensions**.
* The tensor product can be implemented in NumPy using the **tensordot()** function.
* The function takes as arguments the two tensors to be multiplied and the axis on which to sum the products over, called the sum reduction. 
* **To calculate the tensor product, also called the tensor dot product in NumPy, the axis must be set to 0**.

https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html

**numpy.tensordot(*a, b, axes=2*)**

### Tensordot with vectors

In [8]:
from numpy import tensordot

a = array([1,2])
b = array([3,4])
c = tensordot(a, b, axes=0)
print(a.shape)
print(b.shape)
print(c.shape)
print(c)

(2,)
(2,)
(2, 2)
[[3 4]
 [6 8]]


In [9]:
c = tensordot(a, b, axes=1)
print(c)

11


In [10]:
c = a.dot(b)
print(c)

11


### Tensordot with matrices

In [11]:
A = array([[1, 2], [3, 4]])
B = array([[1, 2], [3, 4]])
C = tensordot(A, B, axes=0)
print(A.shape)
print(B.shape)
print(C.shape)
print(C)

(2, 2)
(2, 2)
(2, 2, 2, 2)
[[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]


In [12]:
C = tensordot(A, B, axes=1)
print(C.shape)
print(C)

(2, 2)
[[ 7 10]
 [15 22]]


In [13]:
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]]


In [14]:
C = tensordot(A, B, axes=2)
print(C)

30


### Tensordot with tensors

In [15]:
A = array([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])

B = array([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])

C = tensordot(A, B, axes=0)
print(A.shape)
print(B.shape)
print(C.shape)
print(C)

(3, 2, 2)
(3, 2, 2)
(3, 2, 2, 3, 2, 2)
[[[[[[  1   2]
     [  3   4]]

    [[  5   6]
     [  7   8]]

    [[  9  10]
     [ 11  12]]]


   [[[  2   4]
     [  6   8]]

    [[ 10  12]
     [ 14  16]]

    [[ 18  20]
     [ 22  24]]]]



  [[[[  3   6]
     [  9  12]]

    [[ 15  18]
     [ 21  24]]

    [[ 27  30]
     [ 33  36]]]


   [[[  4   8]
     [ 12  16]]

    [[ 20  24]
     [ 28  32]]

    [[ 36  40]
     [ 44  48]]]]]




 [[[[[  5  10]
     [ 15  20]]

    [[ 25  30]
     [ 35  40]]

    [[ 45  50]
     [ 55  60]]]


   [[[  6  12]
     [ 18  24]]

    [[ 30  36]
     [ 42  48]]

    [[ 54  60]
     [ 66  72]]]]



  [[[[  7  14]
     [ 21  28]]

    [[ 35  42]
     [ 49  56]]

    [[ 63  70]
     [ 77  84]]]


   [[[  8  16]
     [ 24  32]]

    [[ 40  48]
     [ 56  64]]

    [[ 72  80]
     [ 88  96]]]]]




 [[[[[  9  18]
     [ 27  36]]

    [[ 45  54]
     [ 63  72]]

    [[ 81  90]
     [ 99 108]]]


   [[[ 10  20]
     [ 30  40]]

    [[ 50  60]
     [ 70  80]]

   

In [16]:
A = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

B = array([
    [[1,2,3],    [4,5,6],    [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

C = tensordot(A, B, axes=1)
print(A.shape)
print(B.shape)
print(C.shape)
print(C)

(3, 3, 3)
(3, 3, 3)
(3, 3, 3, 3)
[[[[  86   92   98]
   [ 104  110  116]
   [ 122  128  134]]

  [[ 185  200  215]
   [ 230  245  260]
   [ 275  290  305]]

  [[ 284  308  332]
   [ 356  380  404]
   [ 428  452  476]]]


 [[[ 416  452  488]
   [ 524  560  596]
   [ 632  668  704]]

  [[ 515  560  605]
   [ 650  695  740]
   [ 785  830  875]]

  [[ 614  668  722]
   [ 776  830  884]
   [ 938  992 1046]]]


 [[[ 746  812  878]
   [ 944 1010 1076]
   [1142 1208 1274]]

  [[ 845  920  995]
   [1070 1145 1220]
   [1295 1370 1445]]

  [[ 944 1028 1112]
   [1196 1280 1364]
   [1448 1532 1616]]]]


In [17]:
C = tensordot(A, B, axes=2)
print(C.shape)
print(C)

(3, 3)
[[ 828  873  918]
 [2088 2223 2358]
 [3348 3573 3798]]


In [18]:
C = tensordot(A, B, axes=3)
print(C)

8055


* The **tensor product** is the most common form of tensor multiplication that you may encounter, but there are many other types of tensor multiplications that exist, such as the **tensor dot product** and the **tensor contraction**.

### Understanding tensordot

https://stackoverflow.com/questions/41870228/understanding-tensordot

### Outer product

https://en.wikipedia.org/wiki/Outer_product

* In linear algebra, the outer product of two coordinate vectors is a matrix. If the two vectors have dimensions n and m, then their outer product is an n × m matrix.
* More generally, given two tensors (multidimensional arrays of numbers), their outer product is a tensor.
* **The outer product of tensors is also referred to as their tensor product**, and can be used to define the tensor algebra.

The outer product contrasts with:

* **The dot product**, which takes a pair of coordinate vectors as input and produces a scalar.
* **The Kronecker product**, which takes a pair of matrices as input and produces a block matrix.
* **Standard matrix multiplication**.

https://jeremykun.com/2016/03/28/tensorphobia-outer-product/