# Introduction to Singular-Value Decomposition (SVD) for Machine Learning.

1. Singular-Value Decomposition.
2. Calculate Singular-Value Decomposition.
3. Reconstruct Matrix from SVD.
    * When the original matrix is rectangular.
    * When the original matrix is square.
4. Using SVD for Pseudoinverse.
    * Using pinv method from NumPy.
    * Pseudoinverse from scratch via SVD.
5. Using SVD for Dimensionality Reduction.
    * Dimensionality reduction from scratch with SVD.
    * Using TruncatedSVD from scikit-learn.

* Perhaps the most known and widely used matrix decomposition method is the **Singular-Value Decomposition, or SVD**.
* **All matrices have an SVD, which makes it more stable than other methods, such as the eigendecomposition**. As such, it is often used in a wide array of applications including **compressing, denoising, and data reduction**.

## 1. Singular-Value Decomposition.

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

A = U . Sigma . V^T

* A is the real m x n matrix that we wish to decompose.
* U is an m x m matrix.
* Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix.
* V^T is the transpose of an n x n matrix where T is a superscript.

* The diagonal values in the Sigma matrix are known as the **singular values** of the original matrix A.
* The columns of the U matrix are called the **left-singular vectors** of A.
* The columns of V are called the **right-singular vectors** of A.

* *The singular value decomposition (SVD) provides another way to factorize a matrix, into singular vectors and singular values. The SVD allows us to discover some of the same kind of information as the eigendecomposition. However, the SVD is more generally applicable.*
* The SVD is used widely both in the calculation of other matrix operations, such as matrix inverse, but also as a **data reduction method in machine learning**.
* SVD can also be used in **least squares linear regression, image compression, and denoising data**.
* *The singular value decomposition (SVD) has numerous applications in **statistics, machine learning, and computer science**. Applying the SVD to a matrix is like looking inside it with X-ray vision…*

## 2. Calculate Singular-Value Decomposition.

In [1]:
from numpy import array
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])

U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## 3. Reconstruct Matrix from SVD.

### When the original matrix is rectangular

In [2]:
from numpy import diag
from numpy import dot
from numpy import zeros

A = array([[1, 2], [3, 4], [5, 6]])

# Apply SVD
U, s, VT = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(Sigma)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [3]:
# reconstruct original matrix
B = U.dot(Sigma.dot(VT))
print(B)
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1 2]
 [3 4]
 [5 6]]


### When the original matrix is square

In [4]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Apply SVD
U, s, VT = svd(A)

# create n x n Sigma matrix
Sigma = diag(s)
print(Sigma)

[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]


In [5]:
# reconstruct original matrix
B = U.dot(Sigma.dot(VT))
print(B)
print(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4. Using SVD for Pseudoinverse.

* The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal.
* It is also called the **Moore-Penrose Inverse** after two independent discoverers of the method or the **Generalized Inverse**.
* *Matrix inversion is not defined for matrices that are not square. […] When A has more columns than rows, then solving a linear equation using the pseudoinverse provides one of the many possible solutions.*

The pseudoinverse is denoted as **A^+**, where A is the matrix that is being inverted and + is a superscript. The pseudoinverse is calculated using the singular value decomposition of A:

A^+ = V . D^+ . U^T

* A^+ is the pseudoinverse.
* D^+ is the pseudoinverse of the diagonal matrix Sigma.
* U^T is the transpose of U.

We can get U and V from the SVD operation:

A = U . Sigma . V^T

The D^+ can be calculated by creating a diagonal matrix from Sigma, **calculating the reciprocal of each non-zero element in Sigma**, and taking the transpose **if the original matrix was rectangular**.

The pseudoinverse provides one way of solving the **linear regression equation**, specifically when there are more rows than there are columns, which is often the case.

### Using pinv method from NumPy

In [6]:
from numpy.linalg import pinv

A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)

B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


### Pseudoinverse from scratch via SVD

In [7]:
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])

# calculate svd
U, s, VT = svd(A)

# reciprocals of s
d = 1.0 / s

# create m x n D matrix
D = zeros(A.shape)

# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)

# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)

print(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## 5. Using SVD for Dimensionality Reduction.

* Data with a large number of features, such as **more features (columns) than observations (rows)** may be reduced to a smaller subset of features that are most relevant to the prediction problem. The result is **a matrix with a lower rank** that is said to approximate the original matrix.
* To do this we can perform an SVD operation on the original data and **select the top k largest singular values** in Sigma. These columns can be selected from Sigma and the rows selected from V^T.

* An approximate B of the original vector A can then be reconstructed:

    B = U . Sigmak . V^Tk

* In **natural language processing**, this approach can be used on matrices of **word occurrences or word frequencies** in documents and is called **Latent Semantic Analysis or Latent Semantic Indexing**.

* In practice, we can retain and work with a descriptive subset of the data called T. This is a dense summary of the matrix or a projection:

    T = U . Sigmak

* Further, this transform can be calculated and applied to the original matrix A as well as other similar matrices:

    T = V^k . A

### Dimensionality reduction from scratch with SVD

In [8]:
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])

print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [9]:
# Singular-value decomposition
U, s, VT = svd(A)
print(U.shape)
print(s.shape)
print(VT.shape)

(3, 3)
(3,)
(10, 10)


In [10]:
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
print(Sigma.shape)
print(Sigma)

(3, 10)
[[9.69657342e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.25578339e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.48879510e-15 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [11]:
# select k elements
k = 2
Sigma = Sigma[:, :k]
VT = VT[:k, :]
print(Sigma)

[[96.96573419  0.        ]
 [ 0.          7.25578339]
 [ 0.          0.        ]]


In [12]:
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [13]:
# transform
T = U.dot(Sigma)
print(T)

[[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]


In [14]:
# another way to transform
T = A.dot(VT.T)
print(T)

[[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]


* The scikit-learn provides a **TruncatedSVD** class that implements this capability directly.
* The TruncatedSVD class can be created in which you must specify the number of desirable features or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate V^Tk) by calling the **fit()** function, then apply it to the original matrix by calling the **transform()** function. **The result is the transform of A called T** above.

### Using TruncatedSVD from scikit-learn

In [15]:
from sklearn.decomposition import TruncatedSVD

A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])

print(A)

# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


* We can see that the values match those calculated manually above, **except for the sign on some values**. We can expect there to be some instability when it comes to the sign given the nature of the calculations involved and the differences in the underlying libraries and methods used. This instability of sign should not be a problem in practice as long as the transform is trained for reuse.